### ISSUE TITLE
Intermittent Crash on Grouping Tabs in Tab Switcher via Drag and Drop

### ISSUE THREAD

**Issue by 1311-hack1** [wootzapp/wootz-browser#161]
**Description**: 
The app crashed immediately after grouping tabs in the tab switcher using the drag-and-drop feature. This issue has been **observed** **ONLY ONCE,** and attempts to reproduce it on multiple devices have been unsuccessful. It’s unclear if the crash was a one-time occurrence due to specific conditions on the device or a potential underlying issue with the drag-and-drop functionality in tab grouping.

**Steps to (Attempt to) Reproduce:**

1. Open multiple tabs in the Wootzapp browser.
2. Access the tab switcher view.
3. Attempt to group two or more tabs by dragging one tab onto another.
4. Observe if the app crashes upon completing the grouping action.

**Expected Behavior:** Tabs should group successfully without causing the app to crash.

**Observed Behavior:** In only one instance, the app crashed immediately after tabs were grouped via drag-and-drop in the tab switcher.

**Challenges in Reproduction:** This issue has only been seen once, and repeated attempts to replicate it on other devices have failed. This suggests it may be either device-specific, a rare occurrence, or a result of temporary conditions on the device.

**Comment by 1311-hack1** [comment]
@pandey019 issue is fixed, @kritagya-khanna please retest this and comment you response so that it can be closed.

**Comment by kritagya-khanna** [comment]
It is fixed @pandey019 @1311-hack1
