### ISSUE TITLE
When the user is in tab switcher screen, the add extension doesn't open the ext-store

### ISSUE THREAD

**Issue by kritagya-khanna** [wootzapp/wootz-browser#187]
Description:
while in tab switcher screen, When clicking on extension-store button it does not work.

Steps to Reproduce:
1.Open the browser homepage.
2.Click on tab Switcher button(right side of search bar)
3. Click on app menu and try to access ext-store.

Expected Result:
extension store tab should be open 

Actual Result:
no response when we click on the ext-store button

Affected Devices:
All devices

https://github.com/user-attachments/assets/84b31227-8cbc-47ce-aa6b-54474397ad95

**Comment by 1311-hack1** [comment]
@pandey019 this can be closed, as we are adding inbuilt extension store.
