### ISSUE TITLE
Browser crashing whenever I click on more options in clear browsing data.

### ISSUE THREAD

**Issue by kritagya-khanna** [wootzapp/wootz-browser#188]
Description:
When accessing "more options" while clearing browser data from setting "clear browsing data" App crashes

Steps to Reproduce:
1.Open the browser homepage.
2.Go to app menu click on clear browsing data
3.Click on more options

https://github.com/user-attachments/assets/919e5940-2f07-420a-bf79-0e4712116246

**Comment by 1311-hack1** [comment]
@kritagya-khanna please re test this and comment down the test results so that it can be closed. cc: @pandey019

**Comment by kritagya-khanna** [comment]
It is fixed @pandey019 @1311-hack1
