### ISSUE TITLE
 adds `Ethereum:` prefix to recipient, causing transaction error.

### ISSUE THREAD

**Issue by AnandK-2024** [wootzapp/wootz-browser#46]
When I scan a recipient address (`Scan a recipient address using the wallet's QR code scanner.`) for sending cryptocurrency using the web3 wallet, the wallet automatically adds the `"Ethereum:"`prefix to the address. 
This causes an error in the transaction ` -revert with(invalid address)`, and I need to manually remove the prefix each time in order to successfully send the cryptocurrency.

### Expected Behavior

The web3 wallet should not automatically add the "Ethereum" prefix to the recipient address when scanning via QR code. The wallet should accept addresses in a standard format without any modifications.

### Actual Behavior

The web3 wallet adds the "Ethereum" prefix to the recipient address automatically when scanning via QR code, causing an error in the transaction.

![WhatsApp Image 2023-02-16 at 11 54 47](https://user-images.githubusercontent.com/82324643/219285607-332e8ee0-cef9-4553-8dbd-0ad320c588a2.jpeg)

### Recommendation

Create a separate user interface element, such as a `text box` or a `dropdown menu`, to display the `currently connected blockchain network`. This element would `dynamically update ` based on the network selected by the user or automatically detected by the wallet.

---------------
"As a mentee(Winter of Blockchain), I am open to feedback on the codebase and eager to address any flaws with guidance. I'm committed to contributing to the project."

**Comment by sandys** [comment]
Thanks for the bug report.
Can we discuss on discord? Please msg me on the discord server.

**Comment by AnandK-2024** [comment]
Sure, thanks for the prompt reply.
