### ISSUE TITLE
Not able to connect WootzApp when minting NFT

### ISSUE THREAD

**Issue by Joseph2001-braganza** [wootzapp/wootz-browser#49]
I was trying to solve the level1 task , for which I have to mint a nft token using the wootz wallet. I tried searching on the wootz wallet browser on twitter but when I went to Register on a nft , it did not show any option for connecting the wootz wallet , but instead showed other popular wallets. 
Since I am on wootz it should have asked or prompted me for connecting the wootz wallet.
![Screenshot_20230216-175444]( https://user-images.githubusercontent.com/77545228/219367572-56160903-a08d-4053-afc2-4a1eb5cd59af.jpg )

**Comment by sandys** [comment]
hi joseph
we have no control on what a dapp will show on its website.

however, will still work (or should work) if u click on the metamask option.

please try and let us know. your current report is not a bug.

**Comment by Joseph2001-braganza** [comment]
Yes sir  you are right , this is not a bug but was a recommendation, if it
would know that we are currently trying it from the wootzapp it would be
good . It works if I click on other wallets it redirects me to the other
wallets.
It would be good if I have the amount in my wootzapp wallet then I
shouldn't be redirected.
