### ISSUE TITLE
Enable status bar height for notched android devices

### ISSUE THREAD

**Issue by Arioum** [wootzapp/wootz-browser#51]
<h3>A problem that limits browsing functionalities and negatively affects user experience:</h3>

- Browser content blocked by notch-equipped android smartphones.

**Example - Using www.twitter.com**
When we make a search in the browser and arrive at the Twitter home page, the search bar is 70% hidden by the device's notch, making it more difficult to pick it to carry out more related actions.

*Please watch the video below to have a better grasp of this issue:*

https://user-images.githubusercontent.com/95125149/219659089-e3e9d38c-aaa6-4ce0-9970-50867f6e2498.mp4

<br>
Issue observed on the device: <b>Xiaomi POCO F1</b>
<br>
<br>
As seen in the video above, Twitter's search bar is hidden beneath the device's status bar, making it challenging to select. It frequently results in the selection of elements surrounding the targeted selection area. Other elements which are covered by the status bar are completely inaccessible.
<br>
<br>

***NOTE: This issue is addressed from the perspective of the user rather than the developer.***

**Comment by sandys** [comment]
thank you @Arioum for your attempt. however closing this bug respectfully.
