### ISSUE TITLE
WOB Free Mint - Task 1.1 - (Dead Bunny.wtf)

### ISSUE THREAD

**Issue by nishantkumarai** [wootzapp/wootz-browser#54]
Not able to mint due to not connect with wallet and other issue.

https://fair.xyz/collection/deadbunnywtf

Video 👇
[Wootzapp Winter of Blockchain Level 1📺](https://youtu.be/qblmypficig)

**Comment by MayankKataria001** [comment]
Hey, you need to connect your twitter with premint and then follow, like, retweet and sometimes you may need to connect your discord also. Then you will be eligible to register your wallet for free mint.

You can see a complete walkthrough of free minting process in wootzapp with the below link.
https://drive.google.com/file/d/1uhGf_Yd1mH3x26t3dRJQqqBKZS86y4hB/view?usp=share_link

**Comment by nishantkumarai** [comment]
> Hey, you need to connect your twitter with premint and then follow, like, retweet and sometimes you may need to connect your discord also. Then you will be eligible to register your wallet for free mint.
> 
> You can see a complete walkthrough of free minting process in wootzapp with the below link. https://drive.google.com/file/d/1uhGf_Yd1mH3x26t3dRJQqqBKZS86y4hB/view?usp=share_link

Yes, you are right.
